### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Vinz87** [adamgann/gr-tagutils#1]
Hi, I get this error when I perform the make command:

`[  9%] Linking CXX shared library libgnuradio-tagutils.dylib
Undefined symbols for architecture x86_64:
  "pmt::to_complex(boost::intrusive_ptr<pmt::pmt_base>)", referenced from:
      gr::tagutils::tag_extract_cc_impl::search_for_tag(int, int) in tag_extract_cc_impl.cc.o
  "pmt::get_PMT_NIL()", referenced from:
      gr::tagutils::tag_at_offset_ss_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ss_impl.cc.o
      gr::tag_t::tag_t() in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ii_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ii_impl.cc.o
      gr::tag_t::tag_t() in tag_at_offset_ii_impl.cc.o
      gr::tagutils::tag_at_offset_ff_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ff_impl.cc.o
      gr::tag_t::tag_t() in tag_at_offset_ff_impl.cc.o
      gr::tagutils::tag_at_offset_cc_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_cc_impl.cc.o
      ...
  "pmt::dict_has_key(boost::intrusive_ptr<pmt::pmt_base> const&, boost::intrusive_ptr<pmt::pmt_base> const&)", referenced from:
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ss_impl.cc.o
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ii_impl.cc.o
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ff_impl.cc.o
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_cc_impl.cc.o
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_bb_impl.cc.o
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_to_byte_sb_impl.cc.o
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_to_byte_ib_impl.cc.o
      ...
  "pmt::string_to_symbol(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      gr::tagutils::tag_at_offset_ss_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ii_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_ii_impl.cc.o
      gr::tagutils::tag_at_offset_ff_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_ff_impl.cc.o
      gr::tagutils::tag_at_offset_cc_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_cc_impl.cc.o
      gr::tagutils::tag_at_offset_bb_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_bb_impl.cc.o
  "pmt::intrusive_ptr_add_ref(pmt::pmt_base*)", referenced from:
      gr::tagutils::tag_at_offset_ss_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ss_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_ss_impl.cc.o
      gr::basic_block::dispatch_msg(boost::intrusive_ptr<pmt::pmt_base>, boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ss_impl.cc.o
      std::__1::map<boost::intrusive_ptr<pmt::pmt_base>, boost::function<void (boost::intrusive_ptr<pmt::pmt_base>)>, pmt::comparator, std::__1::allocator<std::__1::pair<boost::intrusive_ptr<pmt::pmt_base> const, boost::function<void (boost::intrusive_ptr<pmt::pmt_base>)> > > >::operator[](boost::intrusive_ptr<pmt::pmt_base> const&) in tag_at_offset_ss_impl.cc.o
      boost::function1<void, boost::intrusive_ptr<pmt::pmt_base> >::operator()(boost::intrusive_ptr<pmt::pmt_base>) const in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ii_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ii_impl.cc.o
      gr::tagutils::tag_at_offset_ii_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_ii_impl.cc.o
      ...
  "pmt::intrusive_ptr_release(pmt::pmt_base*)", referenced from:
      gr::tagutils::tag_at_offset_ss_impl::tag_at_offset_ss_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, unsigned int, bool) in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ss_impl::tag_at_offset_ss_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, unsigned int, bool) in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ss_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ss_impl::~tag_at_offset_ss_impl() in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ss_impl::~tag_at_offset_ss_impl() in tag_at_offset_ss_impl.cc.o
      virtual thunk to gr::tagutils::tag_at_offset_ss_impl::~tag_at_offset_ss_impl() in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ss_impl::~tag_at_offset_ss_impl() in tag_at_offset_ss_impl.cc.o
      ...
  "pmt::eqv(boost::intrusive_ptr<pmt::pmt_base> const&, boost::intrusive_ptr<pmt::pmt_base> const&)", referenced from:
      gr::basic_block::has_msg_handler(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ss_impl.cc.o
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ss_impl.cc.o
      std::__1::map<boost::intrusive_ptr<pmt::pmt_base>, boost::function<void (boost::intrusive_ptr<pmt::pmt_base>)>, pmt::comparator, std::__1::allocator<std::__1::pair<boost::intrusive_ptr<pmt::pmt_base> const, boost::function<void (boost::intrusive_ptr<pmt::pmt_base>)> > > >::operator[](boost::intrusive_ptr<pmt::pmt_base> const&) in tag_at_offset_ss_impl.cc.o
      gr::basic_block::has_msg_handler(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ii_impl.cc.o
      gr::basic_block::has_msg_port(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ii_impl.cc.o
      std::__1::map<boost::intrusive_ptr<pmt::pmt_base>, boost::function<void (boost::intrusive_ptr<pmt::pmt_base>)>, pmt::comparator, std::__1::allocator<std::__1::pair<boost::intrusive_ptr<pmt::pmt_base> const, boost::function<void (boost::intrusive_ptr<pmt::pmt_base>)> > > >::operator[](boost::intrusive_ptr<pmt::pmt_base> const&) in tag_at_offset_ii_impl.cc.o
      gr::basic_block::has_msg_handler(boost::intrusive_ptr<pmt::pmt_base>) in tag_at_offset_ff_impl.cc.o
      ...
  "pmt::intern(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      gr::tagutils::tag_at_offset_ss_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ii_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ii_impl.cc.o
      gr::tagutils::tag_at_offset_ff_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_ff_impl.cc.o
      gr::tagutils::tag_at_offset_cc_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_cc_impl.cc.o
      gr::tagutils::tag_at_offset_bb_impl::set_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_at_offset_bb_impl.cc.o
      gr::tagutils::tag_to_byte_sb_impl::set_tag_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_to_byte_sb_impl.cc.o
      gr::tagutils::tag_to_byte_ib_impl::set_tag_key(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in tag_to_byte_ib_impl.cc.o
      ...
  "pmt::from_long(long)", referenced from:
      gr::tagutils::tag_at_offset_ss_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_ss_impl.cc.o
      gr::tagutils::tag_at_offset_ii_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_ii_impl.cc.o
      gr::tagutils::tag_at_offset_ff_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_ff_impl.cc.o
      gr::tagutils::tag_at_offset_cc_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_cc_impl.cc.o
      gr::tagutils::tag_at_offset_bb_impl::check_and_place_tag(unsigned int, unsigned int) in tag_at_offset_bb_impl.cc.o
  "pmt::get_PMT_F()", referenced from:
      gr::tag_t::tag_t() in tag_at_offset_ss_impl.cc.o
      gr::tag_t::tag_t() in tag_at_offset_ii_impl.cc.o
      gr::tag_t::tag_t() in tag_at_offset_ff_impl.cc.o
      gr::tag_t::tag_t() in tag_at_offset_cc_impl.cc.o
      gr::tag_t::tag_t() in tag_at_offset_bb_impl.cc.o
  "pmt::to_double(boost::intrusive_ptr<pmt::pmt_base>)", referenced from:
      gr::tagutils::tag_thresh_switch_impl::work(int, std::__1::vector<void const*, std::__1::allocator<void const*> >&, std::__1::vector<void*, std::__1::allocator<void*> >&) in tag_thresh_switch_impl.cc.o
  "pmt::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, boost::intrusive_ptr<pmt::pmt_base>)", referenced from:
      gr::tagutils::tag_thresh_switch_impl::work(int, std::__1::vector<void const*, std::__1::allocator<void const*> >&, std::__1::vector<void*, std::__1::allocator<void*> >&) in tag_thresh_switch_impl.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libgnuradio-tagutils.dylib] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-tagutils.dir/all] Error 2
make: *** [all] Error 2
`

I'm trying to install it on OS X El Capitan with GNURadio 3.7.10

**Comment by adamgann** [comment]
Sorry for the world's longest bug fix response, I haven't done much development on this module lately. The problem is with linking to the PMT library, works fine in Linux but fails on OS X. 

 The CMakeLists changes I pushed should fix that. I verified with GNU Radio 3.7.10.2 on OS X 10.11.6.

If you built GNU Radio from source you might need to add extra CMake arguments [as suggested on the Wiki](https://wiki.gnuradio.org/index.php/MacInstall#Installing_GNU_Radio_on_Mac_OS_X):

`$ mkdir build`
`$ cd build`
`$ CC=/usr/bin/llvm-gcc CXX=/usr/bin/llvm-g++ cmake -DPYTHON_EXECUTABLE=/opt/local/bin/python2.7 -DPYTHON_INCLUDE_DIR=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Headers -DPYTHON_LIBRARY=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python -DSPHINX_EXECUTABLE=/opt/local/bin/rst2html-2.7.py -DGR_PYTHON_DIR=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages ..`
`$ make`

**Comment by Vinz87** [comment]
thanks for looking into it. I'll try your fix and let you know
